In [147]:
import random, numpy as np

In [10]:
num=random.random() #seudoaleatorio en (0,1)
num

0.42291957152012805

In [22]:
lista=[0,1,2,3,4.5,6,7] #recoger un aleatorio entre la lista
random.choice(lista)

1

In [25]:
ente="propiedad" #letra aleatoria en una cadena
random.choice(ente)

'o'

In [33]:
print("Un número aleatorio de la lista es: ", end="") #uso de parámetro "end"
print(random.choice([1, 4, 8, 10, 3]))

Un número aleatorio de la lista es: 3


In [59]:
num1=random.randrange(20,200000) #aleatorios entre intervalos
num1

65166

In [77]:
random.seed(6) #fijando un número para obtener siempre el mismo pseudoaleatorio
print("El número dado seed(6) es ", end="")
print(random.random())

El número dado seed(6) es 0.793340083761663


In [85]:
listaa=["A","B", "C", "D"] #lista que será desordenada
print("La lista original es ", end=" ")
print(listaa)


La lista original es  ['A', 'B', 'C', 'D']


In [105]:
random.shuffle(listaa) #reordenamiento
print("Después del primer ordenamiento aleatorio ", end="" ) 
print(listaa)

Después del primer ordenamiento aleatorio ['D', 'B', 'C', 'A']


In [114]:
print("El número aleatorio real entre 1 y 100000 es ", end="") #usando la distribución uniforme
print(random.uniform(1, 100000))

El número aleatorio real entre 1 y 100000 es 69822.67615152546


In [128]:
rand_list=[] #lista aleatoria
n=100
for i in range (n):
    rand_list.append(random.randint(0,99))
print(rand_list)

[28, 85, 17, 50, 28, 75, 45, 59, 72, 98, 82, 35, 75, 76, 24, 72, 28, 94, 3, 52, 31, 50, 73, 95, 15, 82, 4, 40, 46, 63, 82, 32, 55, 48, 38, 46, 67, 91, 75, 47, 74, 7, 52, 81, 75, 23, 39, 37, 75, 85, 60, 30, 13, 58, 73, 20, 46, 73, 54, 86, 59, 41, 9, 58, 55, 62, 1, 13, 77, 8, 61, 55, 81, 7, 81, 3, 93, 65, 67, 44, 46, 20, 22, 61, 68, 9, 51, 75, 76, 14, 3, 44, 83, 29, 78, 94, 68, 32, 77, 66]


In [132]:
rand_list

[28,
 85,
 17,
 50,
 28,
 75,
 45,
 59,
 72,
 98,
 82,
 35,
 75,
 76,
 24,
 72,
 28,
 94,
 3,
 52,
 31,
 50,
 73,
 95,
 15,
 82,
 4,
 40,
 46,
 63,
 82,
 32,
 55,
 48,
 38,
 46,
 67,
 91,
 75,
 47,
 74,
 7,
 52,
 81,
 75,
 23,
 39,
 37,
 75,
 85,
 60,
 30,
 13,
 58,
 73,
 20,
 46,
 73,
 54,
 86,
 59,
 41,
 9,
 58,
 55,
 62,
 1,
 13,
 77,
 8,
 61,
 55,
 81,
 7,
 81,
 3,
 93,
 65,
 67,
 44,
 46,
 20,
 22,
 61,
 68,
 9,
 51,
 75,
 76,
 14,
 3,
 44,
 83,
 29,
 78,
 94,
 68,
 32,
 77,
 66]

In [145]:
ma = random.sample(range(1,50),40) #creando lista alternativamente
ma

[43,
 14,
 47,
 27,
 36,
 39,
 35,
 42,
 44,
 32,
 6,
 28,
 49,
 11,
 9,
 13,
 19,
 46,
 10,
 23,
 34,
 22,
 2,
 15,
 7,
 25,
 31,
 8,
 48,
 12,
 40,
 45,
 20,
 17,
 24,
 26,
 41,
 37,
 21,
 5]

In [159]:
matriz=np.random.random((2,5)) #matriz aleatoria
matriz

array([[0.22317858, 0.27490209, 0.42300306, 0.74005827, 0.44186019],
       [0.59242838, 0.33669816, 0.28103654, 0.89452481, 0.00482363]])

In [175]:
na=np.random.randint(3,8,10) #generar listas con numpy
na

array([3, 6, 7, 7, 4, 3, 6, 6, 6, 6])

In [178]:
muestra=np.random.random_sample(4) #muestra aleatoria con numpy
muestra

array([0.54907307, 0.63032407, 0.78802262, 0.76177064])

In [183]:
muestraa=np.random.random_sample(size=(2,2)) #muestra doble, numpy
muestraa

array([[0.77089572, 0.57935742],
       [0.40388854, 0.28776664]])