In [8]:
import pandas as pd, numpy as np

In [10]:
estados={0:"Casa", 1:"Cine", 2:"Restaurante"}
estados

{0: 'Casa', 1: 'Cine', 2: 'Restaurante'}

In [12]:
m_trans=np.array([[.2,.6,.2],[.3,0,.7],[.5,0,.5]]) #matriz de transición asociada por estado
m_trans

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

In [38]:
#Caminata aleatoria en proceso de Markov
n=10 #pasos
inicio_estado=2 #se inicia en "Restaurante"
print(estados[inicio_estado],"->", end=" ")
estado_ant=inicio_estado

while n-1:
    
    actual_estado=np.random.choice([0,1,2],p=m_trans[estado_ant])
    print(estados[actual_estado],"->", end=" ")
    actual_estado=estado_ant
    n-=1
print("Finalizaron las transiciones")
    

Restaurante -> Restaurante -> Restaurante -> Restaurante -> Casa -> Restaurante -> Casa -> Restaurante -> Restaurante -> Casa -> Finalizaron las transiciones


In [48]:
#Simulación Montecarlo
pasos=10**6 #tiende a + infinito
inicio_estado=1
pi=np.array([0,0,0]) #a
pi[inicio_estado]=1
estado_ant=inicio_estado

i=0 

while i < pasos:
    actual_estado=np.random.choice([0,1,2],p=m_trans[estado_ant])
    pi[actual_estado]+=1
    estado_ant=actual_estado
    i+=1
    
print("La distribución estacionaria dado el inicio de estado es ",pi/pasos)



La distribución estacionaria dado el inicio de estado es  [0.351379 0.210954 0.437668]


In [56]:
#Método matricial

pasos=10**2
M=m_trans #matriz de transición
i=0
while i<pasos:
    M=np.matmul(M,m_trans)
    i+=1
    
print("M^n=\n", M)
print("La distribución estacionaria dado el inicio de estado es", M[0])



M^n=
 [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]]
La distribución estacionaria dado el inicio de estado es [0.35211268 0.21126761 0.43661972]


In [62]:
#Valores propios
import scipy.linalg
derecha, izquierda= scipy.linalg.eig(m_trans)
print("vectores propios = \n", izquierda)
print("valores propios = \n", derecha)


vectores propios = 
 [[-0.57735027+0.j          0.70597631+0.j          0.70597631-0.j        ]
 [-0.57735027+0.j         -0.26474112+0.4380559j  -0.26474112-0.4380559j ]
 [-0.57735027+0.j         -0.4412352 -0.21196253j -0.4412352 +0.21196253j]]
valores propios = 
 [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [70]:
#normalización de los vectores
pi2=izquierda[:,0]
pi_norm=[(x/np.sum(pi2)).real for x in pi2]
print("El vector normalizado es \n",pi_norm)


El vector normalizado es 
 [0.3333333333333335, 0.33333333333333337, 0.3333333333333333]


In [73]:
#encontrar probabilidades

def prob(sec,m_trans,pi):
    inicio_estado=sec[0]
    prob=pi[inicio_estado]
    estado_ant=inicio_estado
    return prob

print("La probabilidad para la secuencia es", prob([1,2,2,0],m_trans,pi_norm))


La probabilidad para la secuencia es 0.33333333333333337
