### Listas

In [3]:
#Usando listas

lista_numeros=[0,1,2,3,4,5]

for i in lista_numeros:
    if (i%2==0):
        print(i,"es numero es par")
    else:
        print(i,"es numero es impar")
print("Fin")

0 es numero es par
1 es numero es impar
2 es numero es par
3 es numero es impar
4 es numero es par
5 es numero es impar
Fin


In [24]:
#Listas generando número

import numpy as np
lista_r=np.arange(25)
for k in lista_r:
    if(k%2==0):
        print(k,"es par")
    else:
        print(k,"es impar")
print("Fin. ", "hay ", len(lista_r),"elementos")


0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar
10 es par
11 es impar
12 es par
13 es impar
14 es par
15 es impar
16 es par
17 es impar
18 es par
19 es impar
20 es par
21 es impar
22 es par
23 es impar
24 es par
Fin.  hay  25 elementos


In [29]:
#Listas generando números aleatorios
lista_a=random.sample(range(1, 50), 25)
for j in lista_a:
    if(j%2==0):
        print(j,"es par")
    else:
        print(j,"es impar")
print("Fin. ", "hay ", len(lista_a),"elementos")

30 es par
9 es impar
47 es impar
28 es par
10 es par
15 es impar
42 es par
11 es impar
43 es impar
20 es par
21 es impar
2 es par
24 es par
18 es par
22 es par
34 es par
27 es impar
32 es par
45 es impar
37 es impar
4 es par
33 es impar
26 es par
19 es impar
35 es impar
Fin.  hay  25 elementos


In [33]:
#Tomar de la lista hasta...
x=lista_r[:10]
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
#Tomar de la lista después de
y=lista_r[10:]
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
#Agregar número por ejecución
lista_numeros.append(25)
lista_numeros

[0, 1, 2, 3, 4, 5, 25, 25, 25, 25, 25]

In [51]:
#Extender lista
lista_numeros.extend([100,101])
lista_numeros

[0, 1, 2, 3, 4, 5, 25, 25, 25, 25, 25, 100, 101, 100, 101, 100, 101]

In [54]:
#Unir dos listas
lista_listas=[lista_numeros,lista_r]
lista_listas

[[0, 1, 2, 3, 4, 5, 25, 25, 25, 25, 25, 100, 101, 100, 101, 100, 101],
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24])]

In [57]:
#Arrojar una lista definida por posición
lista_listas[1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Tuplas

In [61]:
tupla=(1,2,3,4)
tupla

(1, 2, 3, 4)

In [66]:
#Por posición
tupla[2]

3

In [67]:
tupla_r=(5,6,7,8)

In [69]:
#Crear lista de tuplas
lista_tupla=(tupla,tupla_r)
lista_tupla

((1, 2, 3, 4), (5, 6, 7, 8))

In [76]:
#Tupla multivalor
(Monto, Deuda)="12000,14000".split(",")
print(Monto)
print(Deuda)

12000
14000


### Diccionarios

In [2]:
#Definir diccionario

diccionario_autos ={}
diccionario_autos["March"]="Nissan"
diccionario_autos["Fiesta"]="Ford"
diccionario_autos["Accord"]="Honda"
diccionario_autos["Sportage"]="Kia"

print (diccionario_autos["Accord"])

Honda


In [5]:
#Obtener datos
print(diccionario_autos.get("March"))

Nissan


In [7]:
#Obtener datos no definidos
print(diccionario_autos.get("Camaro"))


None


### Funciones

In [9]:
def haz_la_suma(x,y):
    return x+y
   

In [11]:
haz_la_suma(10,11)

21

In [14]:
#Para x y y números reales
def binomio(x,y,n):
    return (x+y)**n

In [16]:
binomio(2,2,2)

16

In [28]:
#Función dentro de otra función
def funcion_agregada(f,x,y,n):
    return f(x,y,n)


In [29]:
funcion_agregada(binomio,2,2,2)

16

In [41]:
#Función lambda
funcion_cubo=lambda y: y*y*y
print(funcion_cubo(2))


8


In [55]:
#Función que regresa el número anterior
def func_num_ant(n):
    return lambda a : a-n

anterior = func_num_ant(11-10)

print(anterior(11))


10


### Expresiones booleanas

In [58]:
#Verificar veracidad
1==2,2==2,2<4,4>2,4<2

(False, True, True, True, False)

In [64]:
print(True or False)

True


In [67]:
print(True and False)

False


In [70]:
print(1 is 3)

False


<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\kevin\AppData\Local\Temp\ipykernel_26988\453973788.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(1 is 3)


In [74]:
#Verificar condiciones
if 2==4:
    print("Las matemáticas mintieron")
elif 4<2:
    print("Las matemáticas siguen mintiendo")
else:
    print("Las matemáticas nunca mintieron")

Las matemáticas nunca mintieron


### Clases

In [88]:
#Crear una clase usando __init__, que agrega valores a la clase. Notar que "self" es obligatorio por posición pero puede tener otro nombre

class Personas:
    def __init__(se, nombre, edad):
        se.nombre = nombre
        se.edad = edad

p1 = Personas("Joel", 35)

print(p1.nombre)
print(p1.edad)

Joel
35


In [93]:
class Personas:
    def __init__(se, nombre, edad):
        se.nombre = nombre
        se.edad = edad

    def myfunc(se):
        print("Hola. Mi nombre es " + se.nombre)

p1 = Personas("Joel", 35)
p1.myfunc()

Hola. Mi nombre es Joel
